project_name: ece4880proj
exp_name: T3000
use_wandb: True
wandb_entity: miqiuqiu
train_root: /GPFS/public/iNaturalist/processed/train_metainfo_Mammalia14.pkl  
val_root: /GPFS/public/iNaturalist/processed/val_metainfo_Mammalia14.pkl
data_size: 384
num_workers: 8
batch_size: 8
metainfo_dims : [14]
comb_type : MLP_1
model_name: swin-t
pretrained: ~
optimizer: SGD
max_lr: 0.0005
wdecay: 0.0005
max_epochs: 50
warmup_batchs: 800
use_amp: True
use_fpn: True
fpn_size: 1536
use_selection: True
num_classes: 234
num_selects: 
  layer1: 1024
  layer2: 512
  layer3: 128
  layer4: 64
use_combiner: True
lambda_b: 0.5
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0
update_freq: 2
log_freq: 100
eval_freq: 10